name: Publish

on: pull_request

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Compile
        run: |
          npm ci
          ENV=staging npm run compile
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/dist/

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: compile
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
